#!/bin/bash
# Declearing Machine PATH
export RCOMMANDS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# IMPORTS:
# prompts (to perform commands)
source "$RCOMMANDS_ROOT/prompts/push.sh" # as push
source "$RCOMMANDS_ROOT/prompts/pull.sh" # as pull
source "$RCOMMANDS_ROOT/prompts/rename.sh" # as rename
source "$RCOMMANDS_ROOT/prompts/create/ignore.sh" # as gitignore
# Importing Help Command
source "$RCOMMANDS_ROOT/prompts/help.sh" # as help

COMMAND="$1"


case "$COMMAND" in
  push)
    push "$2" "$3" "$4" 
    ;;
  pull)
    pull "$2" "$3" "$4"
    ;;
  rename)
    rename "$2" "$3" "$4"
    ;;
  ignore)
    ignore "$2" "$3" "$4"
    ;;
    #
    # Help Generator
    #
  help)
    help
    ;;
  *)
    echo "Unknown command: $COMMAND"
    echo "Available commands: init, status, push"
    ;;
esac