#!/bin/bash
# Declearing Machine PATH
export RCOMMANDS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# IMPORTS:
# core (to perform commands)
source "$RCOMMANDS_ROOT/prompts/core/push.sh" # as push
source "$RCOMMANDS_ROOT/prompts/core/pull.sh" # as pull
source "$RCOMMANDS_ROOT/prompts/core/rename.sh" # as rename
source "$RCOMMANDS_ROOT/prompts/core/cleanup.sh" # as rename
# Importing: Create
source "$RCOMMANDS_ROOT/prompts/create/readme.sh" # as readme
source "$RCOMMANDS_ROOT/prompts/create/ignore.sh" # as ignore
source "$RCOMMANDS_ROOT/prompts/create/archi.sh" # as archi
source "$RCOMMANDS_ROOT/prompts/create/license.sh" # as license
# Importing: Info
source "$RCOMMANDS_ROOT/prompts/info/userinfo.sh" # as userinfo
source "$RCOMMANDS_ROOT/prompts/info/login.sh" # as login
# Importing Help Command
source "$RCOMMANDS_ROOT/configs/msg.sh" # as msg
source "$RCOMMANDS_ROOT/prompts/help.sh" # as help

COMMAND="$1"

if [[ -z "$COMMAND" ]]; then
    echo "$NO_COMMAND_FOUND : rgit $COMMAND"
    echo "$HELP_COMMAND"
    exit 1
fi


case "$COMMAND" in
# core
  push)
    push "${2:-}" "${3:-}" "${4:-}"
    ;;
  pull)
    pull "${2:-}" "${3:-}" "${4:-}"
    ;;
  rename)
    rename "${2:-}" "${3:-}" "${4:-}"
    ;;
  cleanup)
    cleanup "${2:-}"
    ;;
# Create
  readme)
    readme "${2:-}" "${3:-}" "${4:-}"
    ;;
  ignore)
    ignore "${2:-}"
    ;;
  archi)
    archi "${2:-}"
    ;;
  license)
    license "${2:-}"
    ;;
#Info
  userinfo)
    userinfo "${2:-}"
    ;;
  login)
    login "${2:-}"
    ;;
  help)
    help
    ;;
  *)
    echo "$NO_COMMAND_FOUND : rgit $COMMAND"
    echo "$HELP_COMMAND"
    ;;
esac